DROP TABLE IF EXISTS user;
DROP TABLE IF EXISTS calendar;
DROP TABLE IF EXISTS note;

CREATE TABLE user (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  name TEXT NOT NULL,
  username TEXT UNIQUE NOT NULL,
  password TEXT NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE calendar (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  author_id INTEGER NOT NULL,flas
  created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  title TEXT NOT NULL,
  access_token TEXT NOT NULL,
  FOREIGN KEY (author_id) REFERENCES user (id)
);

CREATE TABLE note (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  author_id INTEGER NOT NULL,
  calendar_id INTEGER NOT NULL,
  description TEXT NOT NULL,
  day INTEGER NOT NULL CHECK(day BETWEEN 1 AND 24),
  opened_at TIMESTAMP DEFAULT NULL,
  FOREIGN KEY (author_id) REFERENCES user (id),
  FOREIGN KEY (calendar_id) REFERENCES calendar (id)
);